### PR TITLE
nit: fix parameter

### PR DESCRIPTION
**Pull request by knowbody**
this is a little typo I found in the parameter name

### CODE REVIEW

**Comment by zth** [comment]
Sorry, totally missed this!

So, this is a bit interesting. I can't remember exactly which version (either `7.0.0` or `7.0.2-dev.1` or similar), but BuckleScript actually recently changed to allow the name `method` rather than `method_`, which is why it's changed there.

But I'm guessing you've bumped into that not actually working, right?

Thanks for PRing!

**Comment by knowbody** [comment]
I was trying it on 7.0.1 and yeah was running into this issue

**Comment by zth** [comment]
Yeah, the change is probably in `7.0.2-dev.1` then. I'll apply this and we can change it back later when it makes sense and it's released officially in BS. Thanks!

**Comment by knowbody** [comment]
thanks

**Pull request merged**
