### PR TITLE
Update to latest experimental version of react and relay

### PR DESCRIPTION
**Pull request by sorenhoyer**
While waiting for the PR in reason-react to be merged, I added a couple of temporary bindings that lets us update to latest react and relay experimental versions.

### CODE REVIEW

**Review by zth — COMMENTED** [review]
😍 This is great!

Would you mind adding to the changelog + updating the docs (the versions are outlined in the Getting Started-section) too? 😄

**Comment by zth** [comment]
@sorenhoyer One final thing, really sorry about this 🙈 But would you mind reverting the changes to `example/src/SingleTicketWorkingGroup.re`? They're right, it's just that I typically do a single commit after a new release where I upgrade the example, to show people how to migrate to the new version. So I'd like to do that change there instead.

Thanks again for your contribution, this is really valuable!

**Comment by sorenhoyer** [comment]
@zth the changes to that file has now been reverted as you suggested.

**Comment by sorenhoyer** [comment]
I cal also revert all changes in the example if you prefer that? :-)

**Comment by zth** [comment]
@sorenhoyer oh yes, I missed the others, please do if you can! I'll merge as soon as that's done.

**Comment by sorenhoyer** [comment]
@zth reverted all changes to the example

**Comment by zth** [comment]
Thank you! 🙏

**Pull request merged**
